services:
  app:
    build:
      dockerfile: ./Dockerfile.dev
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge
