services:
  app:
    container_name: personal-finance-api-development-app
    build:
      dockerfile: ./Dockerfile.development
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge

volumes:
  db-data:
