services:
  db:
    image: postgres:13
    command: postgres -p 5432 -c datestyle='dmy'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - 5432:5432

  app:
    build:
      dockerfile: ./Dockerfile.production
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge

volumes:
  db-data:
