# services:
#   db:
#     image: postgres
#     restart: always
#     shm_size: 128mb
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=examplepassword
#       - POSTGRES_DB=mydatabase
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     networks:
#       - app-network
#     ports:
#       - 5432:5432

#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080
    
# networks:
#   app-network:
#     driver: bridge

# volumes:
#   db-data:

# $ docker exec -it personal-finance-api-db-1 psql -U postgres -W mydatabase

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_INITDB_ARGS: '-c datestyle="iso, dmy"'
      # POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_DB: mydatabase
    networks:
      - app-network
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
