services:
  db:
    container_name: personal-finance-api-staging-db
    image: postgres:13
    command: postgres -p 5433 -c datestyle='dmy'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - 5433:5433

  app:
    container_name: personal-finance-api-staging-app
    build:
      dockerfile: ./Dockerfile.staging
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge

volumes:
  db-data:
