FROM node:latest
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV PORT=3000
ENV NODE_ENV=staging
RUN npm run build
RUN npm install pm2 -g
CMD npm run db:migrate && pm2 start process.yml && tail -f /dev/null
EXPOSE 3000
