/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
    // Deletes ALL existing entries
    await knex('matcher').del()
    await knex('matcher').insert([
        {
            id: 1,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            match: 'ASDA SUPERSTORE',
            match_type: 'any',
            case_sensitive: false
        },
        {
            id: 2,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            match: 'HOME BARGAINS',
            match_type: 'any',
            case_sensitive: false
        },
        {
            id: 3,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            match: 'TESCO',
            match_type: 'any',
            case_sensitive: false
        },
        {
            id: 4,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            match: 'ALDI',
            match_type: 'any',
            case_sensitive: false,
        },
        {
            id: 5,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            match: 'NON-GBP PURCH FEE',
            match_type: 'any',
            case_sensitive: false,
        },
        {
            id: 6,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            match: 'NON-GBP TRANS FEE',
            match_type: 'any',
            case_sensitive: false,
        },
        {
            id: 7,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            match: 'PAYPAL *PATREONIRE',
            match_type: 'any',
            case_sensitive: false,
        },
        {
            id: 8,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            match: 'PAYPAL *PATREON M',
            match_type: 'any',
            case_sensitive: false,
        },
        {
            id: 9,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            match: 'PAYPAL *PATREON M',
            match_type: 'any',
            case_sensitive: false,
        },
        {
            id: 10,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            match: 'FIRST GLASGOW',
            match_type: 'any',
            case_sensitive: false,
        },
        {
            id: 11,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            match: 'PATTERTON STN SST',
            match_type: 'any',
            case_sensitive: false,
        },
        {
            id: 12,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            match: 'OGPS-GP',
            match_type: 'any',
            case_sensitive: false,
        },
        {
            id: 13,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            match: 'GOCARDLESS',
            match_type: 'any',
            case_sensitive: false,
        },
        {
            id: 14,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            match: 'SPOTIFY',
            match_type: 'any',
            case_sensitive: false,
        },
        {
            id: 15,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            match: 'Decathlon UK Limit',
            match_type: 'any',
            case_sensitive: false,
        },
        {
            id: 16,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            match: 'NATWEST HRPS PAYRO',
            match_type: 'any',
            case_sensitive: false,
        },
        {
            id: 17,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            match: 'GOOGLE\*CLOUD',
            match_type: 'any',
            case_sensitive: false,
        },
        {
            id: 18,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            match: 'VODAFONE',
            match_type: 'start',
            case_sensitive: false,
        },
        {
            id: 19,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            match: 'INDEPENDENT CARE P',
            match_type: 'exact',
            case_sensitive: true,
        },
        {
            id: 20,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            match: 'JULIAN MAUGER',
            match_type: 'exact',
            case_sensitive: true,
        },
    ])
    await knex('category').del()
    await knex('category').insert([
        {
            id: 1,
            label: 'food',
            description: 'Any food related items or meals.',
            colour: '#509af3',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 2,
            label: 'support',
            description: 'Any funds supporting organisations or other voluntery donations.',
            colour: '#4c9a2a',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 3,
            label: 'travel',
            description: 'Travel expenses.',
            colour: '#ee204d',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 4,
            label: 'health',
            description: 'Health related costs.',
            colour: '#008080',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 5,
            label: 'subscriptions',
            description: 'Monthly optional subscriptions.',
            colour: '#ecf0f1',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 6,
            label: 'bike',
            description: 'Expenses related to the ebike.',
            colour: '#fb8d1a',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 7,
            label: 'income',
            description: 'Any income sources.',
            colour: '#d8737f',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 8,
            label: 'work',
            description: 'Work related expenses.',
            colour: '#f1c40f',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 9,
            label: 'phone',
            description: 'Phone bill.',
            colour: '#d3dd18',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 10,
            label: 'dentist',
            description: 'Dental bills.',
            colour: '#5650de',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 11,
            label: 'therapy',
            description: 'Therapy bills.',
            colour: '#881798',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 12,
            label: 'home',
            description: 'Related to home utilities & life comfort.',
            colour: '#e84a5f',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 13,
            label: 'investment',
            description: 'Savings & investments.',
            colour: '#0d1017',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 14,
            label: 'rent',
            description: 'Rent, motgage & factor fees.',
            colour: '#34495e',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 15,
            label: 'gifts',
            description: 'Gifts & presents for others.',
            colour: '#8857e6',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 16,
            label: 'garden',
            description: 'Garden related expendature.',
            colour: '#2f1629',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 17,
            label: 'clothes',
            description: 'Clothing & accessories.',
            colour: '#16a085',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
    ])
    await knex('category_matcher').del()
    await knex('category_matcher').insert([
        {
            id: 1,
            category_id: 1,
            matcher_id: 1,
        },
        {
            id: 2,
            category_id: 1,
            matcher_id: 2,
        },
        {
            id: 3,
            category_id: 1,
            matcher_id: 3,
        },
        {
            id: 4,
            category_id: 1,
            matcher_id: 4,
        },
        {
            id: 5,
            category_id: 2,
            matcher_id: 5,
        },
        {
            id: 6,
            category_id: 2,
            matcher_id: 6,
        },
        {
            id: 7,
            category_id: 2,
            matcher_id: 7,
        },
        {
            id: 8,
            category_id: 2,
            matcher_id: 8,
        },
        {
            id: 9,
            category_id: 2,
            matcher_id: 9,
        },
        {
            id: 10,
            category_id: 3,
            matcher_id: 10,
        },
        {
            id: 11,
            category_id: 3,
            matcher_id: 11,
        },
        {
            id: 12,
            category_id: 4,
            matcher_id: 12,
        },
        {
            id: 13,
            category_id: 4,
            matcher_id: 13,
        },
        {
            id: 14,
            category_id: 5,
            matcher_id: 14,
        },
        {
            id: 15,
            category_id: 6,
            matcher_id: 15,
        },
        {
            id: 16,
            category_id: 7,
            matcher_id: 16,
        },
        {
            id: 17,
            category_id: 8,
            matcher_id: 17,
        },
        {
            id: 18,
            category_id: 9,
            matcher_id: 18,
        },
        {
            id: 19,
            category_id: 10,
            matcher_id: 19,
        },
        {
            id: 20,
            category_id: 11,
            matcher_id: 20,
        },
    ])
}

// SWITCH(
//   "ASDA SUPERSTORE", "food",
//   "HOME BARGAINS", "food",

//   "NON-GBP PURCH FEE", "support",
//   "NON-GBP TRANS FEE", "support",
//   "PAYPAL *PATREONIRE", "support",
//   "PAYPAL *PATREON M", "support",
//   "PAYPAL *PATREON M", "support",

//   "FIRST GLASGOW", "travel",
//   "PATTERTON STN SST", "travel",

//   "OGPS-GP", "health",
//   "OGPS-GP", "health",
//   "GOCARDLESS", "health",

//   "SPOTIFY", "subscriptions",
//   "Decathlon UK Limit", "bike",
//   "NATWEST HRPS PAYRO", "income",
//   "GOOGLE*CLOUD KR33W", "work",
//   "VODAFONE LTD", "phone",
//   "INDEPENDENT CARE P", "dentist",
//   "JULIAN MAUGER", "therapy",
// )