/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
    // Deletes ALL existing entries
    await knex('scenario').del()
    await knex('scenario').insert([
        {
            id: 1,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            start_date: new Date('6 feb 2024'),
            end_date: null,
            title: 'BAU',
            description: 'Buisness as usual',
            start_ballance: 1943,
        },
        
    ])
    await knex('transactor').del()
    await knex('transactor').insert([
        {
            id: 1,
            scenario_id: 1,
            description: 'Mortgage',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            value: 1168.55,
            is_addition: false,
        },
        {
            id: 2,
            scenario_id: 1,
            description: 'Salary',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            value: 3083.28,
            is_addition: true,
        },
        {
            id: 3,
            scenario_id: 1,
            description: 'Food',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            value: 100,
            is_addition: false,
        },
        {
            id: 4,
            scenario_id: 1,
            description: 'Keep',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            value: 100,
            is_addition: false,
        },
        {
            id: 5,
            scenario_id: 1,
            description: 'Juline',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            value: 60,
            is_addition: false,
        },
        {
            id: 6,
            scenario_id: 1,
            description: 'Council Tax',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            value: 166,
            is_addition: false,
        },
        {
            id: 7,
            scenario_id: 1,
            description: 'Energy',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            value: 160,
            is_addition: false,
        },
        {
            id: 8,
            scenario_id: 1,
            description: 'Dentist',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            value: 22,
            is_addition: false,
        },
        {
            id: 9,
            scenario_id: 1,
            description: 'Phone',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            value: 39.18,
            is_addition: false,
        },
        {
            id: 10,
            scenario_id: 1,
            description: 'Home Insurance',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            value: 25.25,
            is_addition: false,
        },
        {
            id: 11,
            scenario_id: 1,
            description: 'BSCX Bonus Ball',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            value: 52,
            is_addition: false,
        },
        {
            id: 12,
            scenario_id: 1,
            description: 'Virgin',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            value: 68,
            is_addition: false,
        },
        {
            id: 13,
            scenario_id: 1,
            description: 'Harley Street',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            value: 30,
            is_addition: false,
        },
        {
            id: 14,
            scenario_id: 1,
            description: 'Spotify',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            value: 10.99,
            is_addition: false,
        },
        {
            id: 15,
            scenario_id: 1,
            description: 'Free Code Camp',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            value: 4.61,
            is_addition: false,
        },
        {
            id: 16,
            scenario_id: 1,
            description: 'Website',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            value: 25.5,
            is_addition: false,
        },
        {
            id: 17,
            scenario_id: 1,
            description: 'Patreon',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            value: 23.54,
            is_addition: false,
        },
    ])
    await knex('scheduler').del()
    await knex('scheduler').insert([
        {
            id: 1,
            transactor_id: 1,
            scheduler_code: 'DAY',
            day: 22,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 2,
            transactor_id: 2,
            scheduler_code: 'SCALAR',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            step: 31,
            start_date: new Date('18 january 2024').toISOString(),
        },
        {
            id: 3,
            transactor_id: 3,
            scheduler_code: 'SCALAR',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            step: 7,
            start_date: new Date('6 january 2024').toISOString(),
        },
        {
            id: 4,
            transactor_id: 4,
            scheduler_code: 'DAY',
            day: 23,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 5,
            transactor_id: 5,
            scheduler_code: 'SCALAR',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            step: 7,
            start_date: new Date('1 january 2024').toISOString(),
        },
        {
            id: 6,
            transactor_id: 6,
            scheduler_code: 'DAY',
            day: 29,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 7,
            transactor_id: 7,
            scheduler_code: 'DAY',
            day: 22,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 8,
            transactor_id: 8,
            scheduler_code: 'DAY',
            day: 5,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 9,
            transactor_id: 9,
            scheduler_code: 'DAY',
            day: 5,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 10,
            transactor_id: 10,
            scheduler_code: 'DAY',
            day: 5,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 11,
            transactor_id: 11,
            scheduler_code: 'SCALAR',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
            step: 365,
            start_date: new Date('12 february 2024').toISOString(),
        },
        {
            id: 12,
            transactor_id: 12,
            scheduler_code: 'DAY',
            day: 15,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 13,
            transactor_id: 13,
            scheduler_code: 'DAY',
            day: 19,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 14,
            transactor_id: 14,
            scheduler_code: 'DAY',
            day: 28,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 15,
            transactor_id: 15,
            scheduler_code: 'DAY',
            day: 14,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 16,
            transactor_id: 16,
            scheduler_code: 'DAY',
            day: 4,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            id: 17,
            transactor_id: 17,
            scheduler_code: 'DAY',
            day: 2,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
    ])
}
