const dayjs = require('dayjs')
const customParseFormat = require('dayjs/plugin/customParseFormat')

dayjs.extend(customParseFormat)

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
    await knex('transaction').del()
    await knex('transaction').insert([
        {
            id: 1, 
            date: new Date('2 march 2023').getTime(),
            transaction_type: 'DEB',
            description: 'FIRST GLASGOW',
            debit: 2.85,
            credit: 0,
            ballance: 22636.68,
            created_on: new Date('14 april 2023').toISOString(),
            updated_on: new Date('14 april 2023').toISOString(),
            category_id: 3,
        },
        {
            date: dayjs('01/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'SO',
            description: 'SANDRA VEITCH',
            debit: 700,
            credit: 0,
            ballance: 20892.76,
            category_id: 14,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('01/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'HOME BARGAINS',
            debit: 1.9,
            credit: 0,
            ballance: 20890.86,
            category_id: 1,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('01/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'BOOTS 1581',
            debit: 12.5,
            credit: 0,
            ballance: 20878.36,
            category_id: 4,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('02/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'PAYPAL *PATREONIRE',
            debit: 6,
            credit: 0,
            ballance: 20872.36,
            category_id: 2,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('02/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'CLOUD 2SQW36',
            debit: 17,
            credit: 0,
            ballance: 20855.36,
            category_id: 8,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('02/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'PAYPAL *PATREON  M',
            debit: 17.68,
            credit: 0,
            ballance: 20837.68,
            category_id: 2,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('03/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'HOME BARGAINS',
            debit: 1.99,
            credit: 0,
            ballance: 20835.69,
            category_id: 1,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('03/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'Ashers Bakery',
            debit: 2.75,
            credit: 0,
            ballance: 20832.94,
            category_id: 1,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('03/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'ALDI STORES',
            debit: 3.78,
            credit: 0,
            ballance: 20829.16,
            category_id: 1,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('03/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'CO-OP GROUP FOOD',
            debit: 11.2,
            credit: 0,
            ballance: 20817.96,
            category_id: 1,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('03/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'OGPS-GP',
            debit: 20,
            credit: 0,
            ballance: 20797.96,
            category_id: 4,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('03/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'FPO',
            description: 'SANDRA VEITCH',
            debit: 28,
            credit: 0,
            ballance: 20769.96,
            category_id: 15,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('06/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'SCOTRAILCOM',
            debit: 31.25,
            credit: 0,
            ballance: 20738.71,
            category_id: 3,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('06/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'TESCO STORES 2046',
            debit: 5.75,
            credit: 0,
            ballance: 20732.96,
            category_id: 1,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('06/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'MIKES BIKES',
            debit: 25,
            credit: 0,
            ballance: 20707.96,
            category_id: 6,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('06/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'GLASGOW CENTRAL ST',
            debit: 2.55,
            credit: 0,
            ballance: 20705.41,
            category_id: 3,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('06/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'TESCO STORES 2046',
            debit: 2.75,
            credit: 0,
            ballance: 20702.66,
            category_id: 1,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('06/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'AMZNMktplace', // 'Spoke Wrench'
            debit: 4.99,
            credit: 0,
            ballance: 20697.67,
            category_id: 6,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('06/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'AMZNMktplace', // 'Brush Set'
            debit: 12.49,
            credit: 0,
            ballance: 20685.18,
            category_id: 6,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('06/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'FPO',
            description: 'JULIAN MAUGER',
            debit: 60,
            credit: 0,
            ballance: 20625.18,
            category_id: 11,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('07/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'AMZNMktplace', // 'caliper'
            debit: 22.99,
            credit: 0,
            ballance: 20602.19,
            category_id: 12,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('08/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DD',
            description: 'VODAFONE LTD',
            debit: 29.11,
            credit: 0,
            ballance: 20573.08,
            category_id: 9,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('08/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'Amazon.co.uk*1R9AU', // 'Muc-Off chain cleaner'
            debit: 8.49,
            credit: 0,
            ballance: 20564.59,
            category_id: 6,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('08/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'AMZNMktplace',
            debit: 17.88,
            credit: 0,
            ballance: 20546.71,
            category_id: 6,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('08/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'Amazon.co.uk*1R84F', // 'Park Tool Brush Cleaner + Brush Set'
            debit: 47.94,
            credit: 0,
            ballance: 20498.77,
            category_id: 6,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('08/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'WWW.CLEARCHEMIST.C',
            debit: 95.2,
            credit: 0,
            ballance: 20403.57,
            category_id: 4,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('08/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'AMZNMktplace', // 'Brake Pads'
            debit: 7.99,
            credit: 0,
            ballance: 20395.58,
            category_id: 6,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('09/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'TESCO-STORES-6050',
            debit: 1.25,
            credit: 0,
            ballance: 20394.33,
            category_id: 1,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('09/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'GOGARBURN RESTAURA',
            debit: 2.25,
            credit: 0,
            ballance: 20392.08,
            category_id: 1,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('09/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'TESCO STORES 5189',
            debit: 2.45,
            credit: 0,
            ballance: 20389.63,
            category_id: 1,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('09/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'GOGARBURN RESTAURA',
            debit: 2.55,
            credit: 0,
            ballance: 20387.08,
            category_id: 1,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('09/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'GLASGOW CENTRAL ST',
            debit: 2.55,
            credit: 0,
            ballance: 20384.53,
            category_id: 3,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('09/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'GOGARBURN RESTAURA',
            debit: 6.1,
            credit: 0,
            ballance: 20378.43,
            category_id: 1,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('09/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'HAYMARKET EDINBURG',
            debit: 9.2,
            credit: 0,
            ballance: 20369.23,
            category_id: 3,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('09/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'GLASGOW QUEEN STRE',
            debit: 12,
            credit: 0,
            ballance: 20357.23,
            category_id: 3,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('09/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'PATTERTON STN SST',
            debit: 12,
            credit: 0,
            ballance: 20345.23,
            category_id: 3,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('09/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'TESCO-STORES-6050',
            debit: 23.95,
            credit: 0,
            ballance: 20321.28,
            category_id: 1,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('13/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'AMZNMktplace', // 'Brake Cable'
            debit: 5.98,
            credit: 0,
            ballance: 20315.3,
            category_id: 6,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('13/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'AMZNMktplace', // 'Shifter Cable'
            debit: 6.99,
            credit: 0,
            ballance: 20308.31,
            category_id: 6,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('13/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'DOMINO S PIZZA',
            debit: 12.58,
            credit: 0,
            ballance: 20295.73,
            category_id: 1,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('13/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'TESCO-STORES-6050',
            debit: 17.65,
            credit: 0,
            ballance: 20278.08,
            category_id: 1,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('13/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'Amazon.co.uk*1R14F', // 'Girls Who Lie Book'
            debit: 7.99,
            credit: 0,
            ballance: 20270.09,
            category_id: 15,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('13/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'ASDA SUPERSTORE',
            debit: 31.55,
            credit: 0,
            ballance: 20238.54,
            category_id: 1,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('13/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'AMZNMktplace', // 'Crates'
            debit: 52.8,
            credit: 0,
            ballance: 20185.74,
            category_id: 12,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('13/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'ROUKEN GLEN GARDEN',
            debit: 61.41,
            credit: 0,
            ballance: 20124.33,
            category_id: 16,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('13/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'FPO',
            description: 'JULIAN MAUGER',
            debit: 60,
            credit: 0,
            ballance: 20064.33,
            category_id: 11,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('14/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'AMZNMktplace', // 'Calander'
            debit: 6.48,
            credit: 0,
            ballance: 20057.85,
            category_id: 12,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('15/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DD',
            description: 'GOCARDLESS',
            debit: 25,
            credit: 0,
            ballance: 20032.85,
            category_id: 4,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('15/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'FREECODECAMP.ORG',
            debit: 4.2,
            credit: 0,
            ballance: 20028.65,
            category_id: 2,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('15/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'NON-GBP TRANS FEE',
            debit: 0.12,
            credit: 0,
            ballance: 20028.53,
            category_id: 2,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('15/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'NON-GBP PURCH FEE',
            debit: 0.5,
            credit: 0,
            ballance: 20028.03,
            category_id: 2,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('16/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'AMZNMktplace', // 'Shifter Cable Housing'
            debit: 10.95,
            credit: 0,
            ballance: 20017.08,
            category_id: 6,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('17/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'BGC',
            description: 'NATWEST HRPS PAYRO',
            debit: 0,
            credit: 3881.42,
            ballance: 23898.5,
            category_id: 7,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('20/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'AMZNMktplace', // 'Huawei Freelace'
            debit: 129.99,
            credit: 0,
            ballance: 23768.51,
            category_id: 12,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('20/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'FPO',
            description: 'JULIAN MAUGER',
            debit: 60,
            credit: 0,
            ballance: 23708.51,
            category_id: 11,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('21/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DD',
            description: 'THE LABOUR PARTY',
            debit: 2.62,
            credit: 0,
            ballance: 23705.89,
            category_id: 2,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('24/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'FPO',
            description: 'ZOPA',
            debit: 100,
            credit: 0,
            ballance: 23605.89,
            category_id: 13,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('27/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'AMZNMktplace', // 'Phone Holder'
            debit: 12.99,
            credit: 0,
            ballance: 23592.9,
            category_id: 6,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('27/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'BOOTS 0611',
            debit: 7,
            credit: 0,
            ballance: 23585.9,
            category_id: 4,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('27/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'SUPERDRUG STORES P',
            debit: 7.48,
            credit: 0,
            ballance: 23578.42,
            category_id: 4,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('27/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'ASDA SUPERSTORE',
            debit: 31.15,
            credit: 0,
            ballance: 23547.27,
            category_id: 1,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('27/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'CEX LTD',
            debit: 525,
            credit: 0,
            ballance: 23022.27,
            category_id: 12,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('27/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'FPO',
            description: 'JULIAN MAUGER',
            debit: 60,
            credit: 0,
            ballance: 22962.27,
            category_id: 11,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('27/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'ASDA SUPERSTORE',
            debit: 31.94,
            credit: 0,
            ballance: 22930.33,
            category_id: 1,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('28/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'SPOTIFY',
            debit: 9.99,
            credit: 0,
            ballance: 22920.34,
            category_id: 5,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        },
        {
            date: dayjs('31/03/2023', 'DD/MM/YYYY').valueOf(),
            transaction_type: 'DEB',
            description: 'OGPS-GP',
            debit: 20,
            credit: 0,
            ballance: 22900.34,
            category_id: 4,
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        }
        
    ])
}
