/**
 * Snapshot test utilities.
 *
 * Provides common helpers for snapshot testing with chai-snapshot-matcher,
 * including shared volatile-field ignore lists and a convenience wrapper.
 *
 * Usage:
 *   import 'chai-snapshot-matcher';
 *   import { IGNORE_VOLATILE, snapshotBody } from './snapshotHelper';
 *
 *   it('matches snapshot', function () {
 *     // ...request...
 *     snapshotBody(res.body, this, IGNORE_VOLATILE.USER);
 *   });
 */

import chai from 'chai';
import 'chai-snapshot-matcher';

// Ensure the matcher is only installed once regardless of import order
let installed = false;
export const ensureSnapshotPlugin = () => {
    if (!installed) {
        // chai-snapshot-matcher installs itself as a side-effect when required
        require('chai-snapshot-matcher');
        installed = true;
    }
};

/**
 * Pre-defined ignore lists for common volatile fields.
 * Pass these to matchSnapshot() so timestamps and generated IDs don't
 * cause snapshot mismatches on every test run.
 *
 * Note: the seed data uses fixed UUIDs for most records, so IDs are
 * generally stable. Timestamps (createdOn, updatedOn) always change
 * and must be ignored.
 */
export const IGNORE = {
    /** Timestamps common to nearly every model */
    TIMESTAMPS: ['createdOn', 'updatedOn'],

    /** Auth endpoints also return JWT tokens which are always unique */
    AUTH: ['createdOn', 'updatedOn', 'accessToken', 'refreshToken', 'id'],

    /** Budget/BudgetRow: IDs are generated by uuid() at seed time */
    BUDGET: ['createdOn', 'updatedOn', 'id'],

    /** Card: stable seed IDs, only timestamps vary */
    CARD: ['createdOn', 'updatedOn'],

    /** Category: stable seed IDs, only timestamps vary */
    CATEGORY: ['createdOn', 'updatedOn'],

    /** Matcher: stable seed IDs, only timestamps vary */
    MATCHER: ['createdOn', 'updatedOn'],

    /** Transaction: stable seed IDs, only timestamps and date vary */
    TRANSACTION: ['createdOn', 'updatedOn', 'date'],

    /** Scenario: dates are relative to seed-run time */
    SCENARIO: [
        'createdOn',
        'updatedOn',
        'startDate',
        'endDate',
        'calcStartDate',
        'calcEndDate',
        'displayStartDate',
        'displayEndDate',
    ],

    /**
     * Export/Import: all model timestamps are volatile.
     * IDs are fixed in the import payload and stable in seed data, so they
     * are intentionally NOT ignored — any accidental ID change will surface.
     */
    EXPORT_IMPORT: [
        'createdOn',
        'updatedOn',
        'created_on',
        'updated_on',
        'startDate',
        'endDate',
        'calcStartDate',
        'calcEndDate',
        'displayStartDate',
        'displayEndDate',
        'date',
        'expires',
    ],
} as const;

/**
 * Assert a response body matches its stored snapshot, ignoring the given fields.
 * Convenience wrapper around `expect(body).to.matchSnapshot(ctx, { ignore })`.
 *
 * @param body - The parsed JSON response body to snapshot
 * @param ctx  - Mocha test context (`this` inside a non-arrow `it()` callback)
 * @param ignore - Array of field names to ignore when diffing
 * @param hint - Optional hint to disambiguate multiple snapshots in one `it` block
 */
export const snapshotBody = (
    body: unknown,
    ctx: Mocha.Context,
    ignore: readonly string[],
    hint?: string,
) => {
    const config: { ignore: string[]; hint?: string } = { ignore: [...ignore] };
    if (hint) config.hint = hint;
    chai.expect(body).to.matchSnapshot(ctx, config);
};
