/* eslint-disable @typescript-eslint/no-var-requires */
/* eslint-disable no-undef */
/* eslint-disable quotes */
/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
    // Deletes ALL existing entries
    // await knex('budget').del()
    await knex('budget').insert([
        {
            id: 1,
            card_id: 1,
            name: 'Standard',
            short_desc: 'My typical day-to-day budget.',
            long_desc: 'A sample budget provided with fake data based on real activity with identifying details removed.',
            created_on: new Date().toISOString(),
            updated_on: new Date().toISOString(),
        }
    ])
    // await knex('budget_row').del()
    await knex('budget_row').insert([
        {
            id: 1,
            category_id: 1,
            colour: '#509af3',
            budget_id: 1,
            label: 'Food',
            value: 550,
            var_low_pc: 10,
            var_high_pc: 10,
        },
        {
            id: 2,
            category_id: 2,
            colour: '#4c9a2a',
            budget_id: 1,
            label: 'Support & Donations',
            value: 30,
            var_low_pc: 10,
            var_high_pc: 10,
        },
        {
            id: 3,
            category_id: 3,
            colour: '#ee204d',
            budget_id: 1,
            label: 'Travel',
            value: 80,
            var_low_pc: 10,
            var_high_pc: 10,
        },
        {
            id: 4,
            category_id: 4,
            colour: '#008080',
            budget_id: 1,
            label: 'Healthcare',
            value: 20,
            var_low_pc: 10,
            var_high_pc: 10,
        },
        {
            id: 5,
            category_id: 5,
            colour: '#ecf0f1',
            budget_id: 1,
            label: 'Subscriptions',
            value: 10,
            var_low_pc: 10,
            var_high_pc: 10,
        },
        {
            id: 6,
            category_id: 6,
            colour: '#fb8d1a',
            budget_id: 1,
            label: 'Bike',
            value: 50,
            var_low_pc: 10,
            var_high_pc: 10,
        },
        {
            id: 7,
            category_id: 7,
            colour: '#d8737f',
            budget_id: 1,
            label: 'Income',
            value: 0,
            var_low_pc: 10,
            var_high_pc: 10,
        },
        {
            id: 8,
            category_id: 8,
            colour: '#f1c40f',
            budget_id: 1,
            label: 'Work',
            value: 20,
            var_low_pc: 10,
            var_high_pc: 10,
        },
        {
            id: 9,
            category_id: 9,
            colour: '#d3dd18',
            budget_id: 1,
            label: 'Phone',
            value: 16.20,
            var_low_pc: 10,
            var_high_pc: 10,
        },
        {
            id: 10,
            category_id: 10,
            colour: '#5650de',
            budget_id: 1,
            label: 'Dentist',
            value: 21,
            var_low_pc: 10,
            var_high_pc: 10,
        },
        {
            id: 11,
            category_id: 11,
            colour: '#eca252',
            budget_id: 1,
            label: 'Dog',
            value: 20,
            var_low_pc: 40,
            var_high_pc: 40,
        },
        {
            id: 12,
            category_id: 12,
            colour: '#e84a5f',
            budget_id: 1,
            label: 'Home',
            value: 80,
            var_low_pc: 10,
            var_high_pc: 10,
        },
        {
            id: 13,
            category_id: 13,
            colour: '#0d1017',
            budget_id: 1,
            label: 'Savings',
            value: 0,
            var_low_pc: 10,
            var_high_pc: 10,
        },
        {
            id: 14,
            category_id: 14,
            colour: '#34495e',
            budget_id: 1,
            label: 'Mortgage',
            value: 600,
            var_low_pc: 10,
            var_high_pc: 10,
        },
        {
            id: 15,
            category_id: 15,
            colour: '#8857e6',
            budget_id: 1,
            label: 'Gifts',
            value: 30,
            var_low_pc: 10,
            var_high_pc: 10,
        },
        {
            id: 16,
            category_id: 16,
            colour: '#2f1629',
            budget_id: 1,
            label: 'Garden',
            value: 30,
            var_low_pc: 10,
            var_high_pc: 10,
        },
        {
            id: 17,
            category_id: 17,
            colour: '#16a085',
            budget_id: 1,
            label: 'Clothes',
            value: 30,
            var_low_pc: 10,
            var_high_pc: 10,
        },
        {
            id: 20,
            category_id: 20,
            colour: '#fb701a',
            budget_id: 1,
            label: 'Utilities',
            value: 280,
            var_low_pc: 0,
            var_high_pc: 0,
        },
    ])
}